name: 'gha sls with Python Requirements'
description: 'Javascript action that runs a Serverless deploy using the serverless-python-requirements plugin.'
author: 'yavinenana'
inputs:
  args:
    default: ''
    description: 'Additional arguments you want to set'
    required: false

runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'arrow-up-circle'
  color: 'red'